#coding=utf-8

routers = (
	'/(.*.ico)', 'controller.static.index',
	'/(.*.js)', 'controller.static.index',
	'/(.*.css)', 'controller.static.index',
	'/', 'controller.home.index',

	#'/', 'controller.mysql_change.index',
	'/mysql/index', 'controller.mysql.index',
	'/mysql/change', 'controller.mysql.change',
	'/mysql/view', 'controller.mysql.view',
	'/mysql/delete', 'controller.mysql.delete',
	'/mysql/edit', 'controller.mysql.edit',
	'/mysql/add', 'controller.mysql.add',
	'/mysql_instance/index', 'controller.mysql_instance.index',
	'/mysql_instance/test_conn', 'controller.mysql_instance.test_conn',
	'/mysql_instance/test_privilege', 'controller.mysql_instance.test_privilege',
    '/mysql_instance/set_slave_info', 'controller.mysql_instance.set_slave_info',
    '/mysql_instance/set_time_range', 'controller.mysql_instance.set_time_range',
	'/front/get_ins_by_server_id', 'controller.front.get_ins_by_server_id', 
	'/front/get_ins_db_by_ins_id', 'controller.front.get_ins_db_by_ins_id',
    '/front/get_ins_by_id', 'controller.front.get_ins_by_id',
	'/mysql_change/index', 'controller.mysql_change.index',
	'/mysql_change/save', 'controller.mysql_change.save',
	'/mysql_change/commit', 'controller.mysql_change.commit',
	'/mysql_change/upload', 'controller.mysql_change.upload',
	'/sql_order/index', 'controller.sql_order.index',
	'/sql_order/delete', 'controller.sql_order.delete',
	'/sql_order/view', 'controller.sql_order.view',
	'/sql_order/view_sql','controller.sql_order.view_sql',
	'/sql_order/cancel', 'controller.sql_order.cancel',
	'/sql_order/execute', 'controller.sql_order.execute',
    '/sql_order/api_execute', 'controller.sql_order.api_execute',
	'/sql_order/online', 'controller.sql_order.online',
	'/sql_order/view_process', 'controller.sql_order.view_process',
	'/sql_order/get_process', 'controller.sql_order.new_get_process',
	'/sql_order/my_order', 'controller.sql_order.my_order',
	'/sql_order/my_order/delete', 'controller.sql_order.my_order_delete',
	'/sql_order/rollback', 'controller.sql_order.rollback',
	'/user/login', 'controller.user.login',
	'/user/auth', 'controller.user.auth',
	'/user/logout', 'controller.user.logout',
	'/permission/index', 'controller.permission.index',
	'/permission/commit', 'controller.permission.commit',
	'/inception/config_index', 'controller.inception.config_index',
	'/inception/update_config', 'controller.inception.update_config',
	'/archive/task', 'controller.archive.task',
	'/archive/view', 'controller.archive.view',
    '/archive/new_task', 'controller.archive.new_task',
	'/archive/commit', 'controller.archive.commit',
	'/archive/delete_task', 'controller.archive.delete',
	'/archive/reverse_status', 'controller.archive.reverse_status',
	'/archive/log_index', 'controller.archive.log_index',
	'/archive/delete_log', 'controller.archive.delete_log',
	'/archive/start_now', 'controller.archive.start_now',
	'/feedback/add', 'controller.user.add_feedback',
	'/sql/query_index', 'controller.mysql_change.query_index',
	'/sql/online_query', 'controller.sql.online_query',
	'/sql/export', 'controller.sql.online_query',
	'/sql/add_query_history', 'controller.sql.add_query_history',
	'/sql/is_can_export', 'controller.sql.is_can_export',
    '/index_summary/index', 'controller.index_summary.index',
    '/auto_verify/index', 'controller.auto_verify.index',
    '/auto_verify/update', 'controller.auto_verify.update',
    '/grant/index', 'controller.grant.index',
    '/grant/apply', 'controller.grant.apply',
    '/grant/order', 'controller.grant.order',
    '/grant/order_detail', 'controller.grant.order_detail',
    '/grant/grant', 'controller.grant.grant',
    '/grant/del_order', 'controller.grant.del_order',
    '/slowquery/index', 'controller.slowquery.index',

	'/health/check', 'controller.health.check',
	'/api/get_mysql_servers', 'controller.api.get_mysql_servers',
	'/api/get_ins_by_server_id', 'controller.api.get_ins_by_server_id',
	'/api/get_dbs_by_ins_id', 'controller.api.get_dbs_by_ins_id',
	'/api/del_dbs_by_ins_id', 'controller.api.del_dbs_by_ins_id',
	'/api/add_db_by_ins_id', 'controller.api.add_db_by_ins_id',
	'/api/update_puller_status', 'controller.api.update_puller_status',
	'/api/reset_async', 'controller.api.reset_async',
	'/api/reset_succed', 'controller.api.reset_succed',
    '/api/sql_online_cal_by_db', 'controller.api.sql_online_cal_by_db',
    '/api/online_query_cal', 'controller.api.online_query_cal',
    '/api/order_status_cal', 'controller.api.order_status_cal',
    '/api/test_mysql_conn_state', 'controller.api.test_mysql_conn_state',
    '/api/load_src_dst_info', 'controller.api.load_src_dst_info',
    '/api/add_archive_task', 'controller.api.add_archive_task',
    '/api/get_mysql_priv_list', 'controller.api.get_mysql_priv_list',
    '/api/get_rolling_container_map_list', 'controller.api.get_rolling_container_map_list',
    '/api/get_rolling_nodes_by_service', 'controller.api.get_rolling_nodes_by_service',
    '/api/get_rolling_nodes_str_by_service', 'controller.api.get_rolling_nodes_str_by_service',
    '/api/reverse_archive_task_status', 'controller.api.reverse_archive_task_status',


    #工具api, 查用户在ldap里有的部门
    '/api/get_user_depart',  'controller.api.get_user_depart',

	'/test/test', 'controller.sql_order.test_test',
)